apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: hns
spec:
  shortDescription: Manipulate hierarchical namespaces provided by HNC.
  description: |
    Manipulates hierarchical namespaces provided by the Hierarchical Namespace Controller (HNC).
  version: HNC_IMG_TAG
  homepage: https://github.com/HNC_RELEASE_REPO_OWNER/multi-tenancy/tree/master/incubator/hnc/docs/user-guide
  platforms:
  - uri: https://github.com/HNC_RELEASE_REPO_OWNER/multi-tenancy/releases/download/hnc-HNC_IMG_TAG/kubectl-hns.tar.gz
    selector:
      matchLabels:
        os: linux
        arch: amd64
    sha256: HNC_KREW_TAR_SHA256
    files:
      - from: "bin/kubectl/kubectl-hns_linux_amd64"
        to: "."
      - from: "bin/kubectl/LICENSE"
        to: "."
    bin: "./kubectl-hns_linux_amd64"
  - uri: https://github.com/HNC_RELEASE_REPO_OWNER/multi-tenancy/releases/download/hnc-HNC_IMG_TAG/kubectl-hns.tar.gz
    selector:
      matchLabels:
        os: darwin
        arch: amd64
    sha256: HNC_KREW_TAR_SHA256
    files:
      - from: "bin/kubectl/kubectl-hns_darwin_amd64"
        to: "."
      - from: "bin/kubectl/LICENSE"
        to: "."
    bin: "./kubectl-hns_darwin_amd64"
